# Generated by Django 3.1 on 2022-05-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20220529_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='rate',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
